"""empty message

Revision ID: 0c18b0e7affa
Revises: 5efb254b9f9f
Create Date: 2018-10-10 23:21:29.120979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c18b0e7affa'
down_revision = '5efb254b9f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_comment_language_uc', 'translations', ['language_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_comment_language_uc', 'translations', type_='unique')
    # ### end Alembic commands ###
