"""empty message

Revision ID: 5efb254b9f9f
Revises: aec5753b28c7
Create Date: 2018-10-10 21:36:35.162556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efb254b9f9f'
down_revision = 'aec5753b28c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'languages', ['code'])
    op.create_unique_constraint(None, 'languages', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='unique')
    op.drop_constraint(None, 'languages', type_='unique')
    # ### end Alembic commands ###
